package thesift.datagen;

import java.util.concurrent.CompletableFuture;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.core.HolderLookup;

import thesift.registry.ModBlocks;
import thesift.registry.ModEntities;
import thesift.registry.ModItems;

/** English (en_us) strings. Every player-facing string in the mod is added here. */
final class ModLanguageProvider extends FabricLanguageProvider {
	ModLanguageProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registries) {
		super(output, "en_us", registries);
	}

	@Override
	public void generateTranslations(HolderLookup.Provider registries, TranslationBuilder builder) {
		builder.add("thesift.disclaimer", "Unofficial fan project, not affiliated with or endorsed by Mojang Studios or Microsoft.");
		builder.add("thesift.bed.no_sleep", "You can't sleep here: the Sift never goes quiet");
		builder.add("thesift.bed.rested", "You rest a while; the Tide keeps turning");
		builder.add("itemGroup.thesift", "The Sift");
		builder.add("biome.thesift.singers_meadow", "Singer's Meadow");
		builder.add("biome.thesift.ichor_flats", "Ichor Flats");
		builder.add("biome.thesift.sift_hollows", "Sift Hollows");
		builder.add(ModBlocks.HYMNSTONE, "Hymnstone");
		builder.add(ModBlocks.HYMNSTONE_BRICKS, "Hymnstone Bricks");
		builder.add(ModBlocks.HYMNSTONE_BRICK_STAIRS, "Hymnstone Brick Stairs");
		builder.add(ModBlocks.HYMNSTONE_BRICK_SLAB, "Hymnstone Brick Slab");
		builder.add(ModBlocks.HYMNSTONE_BRICK_WALL, "Hymnstone Brick Wall");
		builder.add(ModBlocks.CRACKED_HYMNSTONE_BRICKS, "Cracked Hymnstone Bricks");
		builder.add(ModBlocks.CHISELED_HYMNSTONE_BRICKS, "Chiseled Hymnstone Bricks");
		builder.add(ModBlocks.HYMNSTONE_STAIRS, "Hymnstone Stairs");
		builder.add(ModBlocks.HYMNSTONE_SLAB, "Hymnstone Slab");
		builder.add(ModBlocks.COBBLED_HYMNSTONE, "Cobbled Hymnstone");
		builder.add(ModBlocks.COBBLED_HYMNSTONE_STAIRS, "Cobbled Hymnstone Stairs");
		builder.add(ModBlocks.COBBLED_HYMNSTONE_SLAB, "Cobbled Hymnstone Slab");
		builder.add(ModBlocks.COBBLED_HYMNSTONE_WALL, "Cobbled Hymnstone Wall");
		builder.add(ModBlocks.SMOOTH_HYMNSTONE, "Smooth Hymnstone");
		builder.add(ModBlocks.SMOOTH_HYMNSTONE_SLAB, "Smooth Hymnstone Slab");
		builder.add(ModBlocks.POLISHED_HYMNSTONE, "Polished Hymnstone");
		builder.add(ModBlocks.POLISHED_HYMNSTONE_STAIRS, "Polished Hymnstone Stairs");
		builder.add(ModBlocks.POLISHED_HYMNSTONE_SLAB, "Polished Hymnstone Slab");
		builder.add(ModBlocks.POLISHED_HYMNSTONE_WALL, "Polished Hymnstone Wall");
		builder.add(ModBlocks.HEALTHY_SCULK, "Healthy Sculk");
		builder.add(ModBlocks.SIFT_SOIL, "Sift Soil");
		builder.add(ModBlocks.HEALTHY_SCULK_GRASS, "Healthy Sculk Grass");
		builder.add(ModBlocks.TALL_HEALTHY_SCULK_GRASS, "Tall Healthy Sculk Grass");
		builder.add(ModBlocks.SONGWOOD_LOG, "Songwood Log");
		builder.add(ModBlocks.SONGWOOD_PLANKS, "Songwood Planks");
		builder.add(ModBlocks.SONGWOOD_LEAVES, "Songwood Leaves");
		builder.add(ModBlocks.SONGWOOD_DRAPES, "Songwood Drapes");
		builder.add(ModBlocks.SONGWOOD_SAPLING, "Songwood Sapling");
		builder.add(ModBlocks.POTTED_SONGWOOD_SAPLING, "Potted Songwood Sapling");
		builder.add(ModBlocks.TIDE_SAND, "Tide Sand");
		builder.add(ModBlocks.TIDE_VENT, "Tide Vent");
		builder.add(ModBlocks.GATESTONE, "Gatestone");
		builder.add(ModBlocks.SIFT_MEMBRANE, "Sift Membrane");
		builder.add(ModBlocks.TIDEWRACK, "Tidewrack");
		builder.add(ModBlocks.ENDURE_BLOOM, "Endure Bloom");
		builder.add(ModBlocks.GLOWCAP, "Glowcap");
		builder.add(ModBlocks.POTTED_GLOWCAP, "Potted Glowcap");
		builder.add(ModBlocks.CHIME_BELL_FLOWER, "Chime Bell Flower");
		builder.add(ModBlocks.POTTED_CHIME_BELL_FLOWER, "Potted Chime Bell Flower");
		builder.add(ModBlocks.LUMEN_BLOOM, "Lumen Bloom");
		builder.add(ModBlocks.LUMEN_LANTERN, "Lumen Lantern");
		builder.add(ModBlocks.ICHOR_LILY, "Ichor Lily");
		builder.add(ModBlocks.HYMNSTONE_COAL_ORE, "Hymnstone Coal Ore");
		builder.add(ModBlocks.HYMNSTONE_COPPER_ORE, "Hymnstone Copper Ore");
		builder.add(ModBlocks.HYMNSTONE_IRON_ORE, "Hymnstone Iron Ore");
		builder.add(ModBlocks.HYMNSTONE_GOLD_ORE, "Hymnstone Gold Ore");
		builder.add(ModBlocks.HYMNSTONE_REDSTONE_ORE, "Hymnstone Redstone Ore");
		builder.add(ModBlocks.HYMNSTONE_LAPIS_ORE, "Hymnstone Lapis Lazuli Ore");
		builder.add(ModBlocks.HYMNSTONE_DIAMOND_ORE, "Hymnstone Diamond Ore");
		builder.add(ModBlocks.HYMNSTONE_EMERALD_ORE, "Hymnstone Emerald Ore");
		builder.add(ModBlocks.ECHO_ORE, "Echo Ore");
		builder.add(ModBlocks.TIDE_ROOTS, "Tide Roots");
		builder.add(ModItems.TIDE_ROOT, "Tide Root");
		builder.add(ModItems.BAKED_TIDE_ROOT, "Baked Tide Root");
		builder.add(ModItems.SONGFRUIT, "Songfruit");
		builder.add(ModItems.GLOWCAP_STEW, "Glowcap Stew");
		builder.add(ModItems.TIDEWRACK_FROND, "Tidewrack Frond");
		builder.add(ModItems.ENDURE_PETAL, "Endure Petal");
		builder.add("subtitles.thesift.tidewrack.open", "Tidewrack opens");
		builder.add("subtitles.thesift.tidewrack.close", "Tidewrack closes");
		builder.add("subtitles.thesift.endure_bloom.open", "Endure bloom opens");
		builder.add("subtitles.thesift.endure_bloom.close", "Endure bloom closes");
		builder.add("subtitles.thesift.flora.pick", "Plant picked");
		builder.add("subtitles.thesift.chime_bell.ring", "Chime bell rings");
		builder.add("subtitles.thesift.chime_bell.hum", "Chime bell hums");
		builder.add("subtitles.thesift.frame.offer", "Soul flows into the frame");
		builder.add("subtitles.thesift.frame.wake", "The frame wakes");
		builder.add("subtitles.thesift.frame.open", "The frame opens");
		builder.add("subtitles.thesift.frame.hum", "The frame hums");
		builder.add("subtitles.thesift.membrane.ambient", "Membrane chimes");
		builder.add("subtitles.thesift.membrane.travel", "Crossing the membrane");
		builder.add("subtitles.thesift.tide.thrive", "The Tide ebbs: Thrive");
		builder.add("subtitles.thesift.tide.flow", "The Tide turns: Flow");
		builder.add("subtitles.thesift.tide.endure", "The Tide rises: Endure");
		builder.add("subtitles.thesift.basin.fill", "Ichor bubbles up");
		builder.add("subtitles.thesift.basin.drain", "Ichor drains away");
		builder.add("subtitles.thesift.ichor.ambient", "Ichor pops");
		builder.add("subtitles.thesift.ichor.evaporate", "Ichor evaporates");
		builder.add("subtitles.thesift.bucket.fill_ichor", "Bucket fills");
		builder.add("subtitles.thesift.bucket.empty_ichor", "Bucket empties");
		builder.add("subtitles.thesift.meadow.loop", "Wind sings in the songwood");
		builder.add("subtitles.thesift.blub.ambient", "Blub squeaks");
		builder.add("subtitles.thesift.blub.listen", "Blub listens");
		builder.add("subtitles.thesift.blub.happy", "Blub is happy");
		builder.add("subtitles.thesift.blub.sing", "Blub sings");
		builder.add("subtitles.thesift.blub.restless", "Blub is restless");
		builder.add("subtitles.thesift.blub.curl", "Blub hums");
		builder.add("subtitles.thesift.blub.splash", "Blub splashes");
		builder.add("subtitles.thesift.blub.topple", "Blubs topple");
		builder.add("subtitles.thesift.blub.hurt", "Blub hurts");
		builder.add("subtitles.thesift.blub.death", "Blub dies");
		builder.add("subtitles.thesift.blub.hop", "Blub hops");
		builder.add("subtitles.thesift.frame.notice", "Your soul stirs toward the frame");
		builder.add("subtitles.thesift.meadow.mood", "A far-off flute");
		builder.add(ModBlocks.ICHOR, "Ichor");
		builder.add(ModItems.ICHOR_BUCKET, "Ichor Bucket");
		builder.add(ModEntities.BLUB, "Blub");
		builder.add(ModEntities.NESTER, "Nester");
		builder.add(ModItems.NESTER_SPAWN_EGG, "Nester Spawn Egg");
		builder.add("subtitles.thesift.nester.ambient", "Nester clicks");
		builder.add("subtitles.thesift.nester.ambient_enduring", "Enduring Nester growls");
		builder.add("subtitles.thesift.nester.hear", "Nester hears something");
		builder.add("subtitles.thesift.nester.gallop", "Nester gallops");
		builder.add("subtitles.thesift.nester.sniff", "Nester sniffs");
		builder.add("subtitles.thesift.nester.hiss", "Nester hisses");
		builder.add("subtitles.thesift.nester.bite", "Nester bites");
		builder.add("subtitles.thesift.nester.guard", "Nester guards");
		builder.add("subtitles.thesift.nester.dodge", "Nester dodges");
		builder.add("subtitles.thesift.nester.stagger", "Nester staggers");
		builder.add("subtitles.thesift.nester.emerge", "Nester surfaces");
		builder.add("subtitles.thesift.nester.burrow", "Nester burrows");
		builder.add("subtitles.thesift.nester.hurt", "Nester hurts");
		builder.add("subtitles.thesift.nester.death", "Nester dies");
		builder.add("subtitles.thesift.nester.step", "Nester steps");
		builder.add("advancements.thesift.heard_you.title", "Heard You");
		builder.add("advancements.thesift.heard_you.description", "Make a sound a Nester hears");
		// Rifts (survival_sift.md §2, §6).
		builder.add(ModEntities.RIFT, "Rift");
		builder.add(ModItems.RIFT_FORK, "Rift Fork");
		builder.add("subtitles.thesift.rift.hum", "Rift hums");
		builder.add("subtitles.thesift.rift.open", "Rift opens");
		builder.add("subtitles.thesift.rift.close", "Rift closes");
		builder.add("subtitles.thesift.rift_fork.strike", "Rift fork rings");
		builder.add("gamerule.thesift.spawn_rifts", "Spawn rifts");
		builder.add("gamerule.thesift.start_in_sift", "Start in the Sift");
		builder.add("advancements.thesift.through_the_rift.title", "Through the Rift");
		builder.add("advancements.thesift.through_the_rift.description", "Step through a rift between the worlds");
		builder.add("advancements.thesift.tuned_in.title", "Tuned In");
		builder.add("advancements.thesift.tuned_in.description", "Make a rift fork, and open the way at will");
		builder.add("advancements.thesift.sift_born.title", "Sift-Born");
		builder.add("advancements.thesift.sift_born.description", "Get a diamond while in the Sift");
		builder.add(ModItems.BLUB_SPAWN_EGG, "Blub Spawn Egg");
		builder.add("advancements.thesift.root.title", "The Sift");
		builder.add("advancements.thesift.root.description", "Walk an Ancient City, where something old is listening");
		builder.add("advancements.thesift.an_offering.title", "An Offering");
		builder.add("advancements.thesift.an_offering.description", "Wake an Ancient City's frame with your experience");
		builder.add("advancements.thesift.where_souls_drift.title", "Where Souls Drift");
		builder.add("advancements.thesift.where_souls_drift.description", "Play music to an awake frame and cross into the Sift");
		builder.add("advancements.thesift.the_tide_turns.title", "The Tide Turns");
		builder.add("advancements.thesift.the_tide_turns.description", "Be in the Sift when the Tide changes");
		builder.add("advancements.thesift.low_tide.title", "Low Tide");
		builder.add("advancements.thesift.low_tide.description", "Gather tidewrack at low tide");
		builder.add("tag.fluid.thesift.ichor", "Ichor");
		builder.add("tag.item.thesift.songwood_logs", "Songwood Logs");
		builder.add("thesift.frame.offering", "Your soul flows into the frame (%s%%)");
		builder.add("thesift.frame.woke", "The frame wakes; it is listening for music");
		builder.add("thesift.frame.awake", "The frame is awake; play it some music");
		builder.add("thesift.frame.no_soul", "You have no experience left to offer");
	}
}
