#!/usr/bin/env python3
"""
Bundle the pure-Luau parts of Trapisque into one file that the standalone `luau`
CLI can run, so the rules engine can be tested without Roblox.

Roblox modules use `require(script.Parent.Foo)`. The bundle recreates a tiny fake
instance tree (folders + module nodes) so those requires resolve to the bundled
module functions.

Usage:
    python3 tools/bundle.py <out.luau> <entry.luau> [more entries...]

The entry file runs after the bundle is set up and can call:
    requireModule("Shared/Game/Engine")
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# filesystem folder -> virtual path prefix
MOUNTS = [
    ("src/shared", "Shared"),
    ("src/client", "Client"),
]


def collect():
    modules = {}
    for folder, prefix in MOUNTS:
        base = os.path.join(ROOT, folder)
        for dirpath, _dirnames, filenames in os.walk(base):
            for fn in sorted(filenames):
                if not (fn.endswith(".lua") or fn.endswith(".luau")):
                    continue
                if fn.endswith(".server.lua") or fn.endswith(".client.lua"):
                    continue
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, base)
                name = rel.rsplit(".", 1)[0].replace(os.sep, "/")
                if name.endswith("/init") or name == "init":
                    raise SystemExit("init modules are not supported by the test bundler: " + full)
                with open(full, "r", encoding="utf-8") as f:
                    modules[prefix + "/" + name] = f.read()
    return modules


HEADER = r'''
-- AUTO-GENERATED by tools/bundle.py. Do not edit.
local __sources = {}
local __nodes = {}
local __cache = {}

local NodeMeta = {}
NodeMeta.__index = function(self, key)
	if key == "Parent" then
		return rawget(self, "__parent")
	elseif key == "Name" then
		return rawget(self, "__name")
	elseif key == "FindFirstChild" then
		return function(node, childName)
			return rawget(node, "__children")[childName]
		end
	elseif key == "WaitForChild" then
		return function(node, childName)
			local c = rawget(node, "__children")[childName]
			assert(c, "WaitForChild: no child " .. tostring(childName) .. " in " .. rawget(node, "__path"))
			return c
		end
	elseif key == "IsA" then
		return function(_node, className)
			return className == "ModuleScript" and rawget(self, "__module") or className == "Folder"
		end
	end
	local child = rawget(self, "__children")[key]
	if child == nil then
		error("bundle: '" .. tostring(key) .. "' is not a child of " .. rawget(self, "__path"), 2)
	end
	return child
end

local function getNode(path)
	local node = __nodes[path]
	if node then
		return node
	end
	local parentPath, name = string.match(path, "^(.*)/([^/]+)$")
	local parent = nil
	if parentPath then
		parent = getNode(parentPath)
	else
		name = path
	end
	node = setmetatable({ __path = path, __name = name, __parent = parent, __children = {} }, NodeMeta)
	if parent then
		rawget(parent, "__children")[name] = node
	end
	__nodes[path] = node
	return node
end

local function requireNode(node)
	local path = rawget(node, "__path")
	if __cache[path] ~= nil then
		return __cache[path]
	end
	local fn = __sources[path]
	assert(fn, "bundle: no module at " .. path)
	__cache[path] = false -- cycle guard
	local result = fn(node, requireNode)
	__cache[path] = result
	return result
end

function requireModule(path)
	return requireNode(getNode(path))
end
'''


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(2)
    out, entries = sys.argv[1], sys.argv[2:]
    modules = collect()
    parts = [HEADER]
    for path, src in sorted(modules.items()):
        parts.append("__sources[%r] = function(script, require)\n%s\nend\n" % (path, src))
        parts.append("rawset(getNode(%r), '__module', true)\n" % path)
    for entry in entries:
        with open(entry, "r", encoding="utf-8") as f:
            parts.append("-- ===== entry: %s =====\ndo\n" % os.path.relpath(entry, ROOT))
            parts.append(f.read())
            parts.append("\nend\n")
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))


if __name__ == "__main__":
    main()
